=== xestoso11/xsd/practica.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

  <xs:element name="cine">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="comidas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="comida" type="xs:string" minOccurs="1" maxOccurs="10"/>
              <xs:element name="bebida" type="xs:string" minOccurs="1" maxOccurs="10" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="entradas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="entrada" minOccurs="0" maxOccurs="10">
                <xs:complexType>

                  <xs:sequence>
                    <xs:element name="id_pelicula">
                     <xs:simpleType>
                       <xs:restriction base="xs:integer">
                          <xs:minExclusive value="0"/>
                          <xs:maxExclusive value="100"/>
                        </xs:restriction>
                     </xs:simpleType>
                    </xs:element>
                  </xs:sequence>

                  <xs:attribute name="id" type="xs:positiveInteger" use="required"/>

                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>


        <xs:element name="peliculas">
        <xs:complexType>
          <xs:sequence>
              <xs:element name="pelicula" minOccurs="1" maxOccurs="10">
                <xs:complexType>

                  <xs:sequence>
                    <xs:element name="nombre_peli" type="xs:string"/>
                    <xs:element name="fecha_de_esteno" type="xs:date" minOccurs="0" maxOccurs="1"/>
                    <xs:element name="hora" type="xs:time" minOccurs="0" maxOccurs="10"/>
                  </xs:sequence>

                  <xs:attribute name="id" type="xs:positiveInteger" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="usuarios">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="usuario" minOccurs="1" maxOccurs="10">
                <xs:complexType>
                  <xs:sequence>

                      <xs:element name="id_usu">
                       <xs:complexType>
                         <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                       </xs:complexType>
                      </xs:element>

                      <xs:element name="nombre" type="xs:string"/>
                      <xs:element name="apellido" type="xs:string" minOccurs="0" maxOccurs="1"/>
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
        </xs:element>


      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== xestoso11/xsd/practica.xml
<?xml version="1.0" encoding="UTF-8"?>



<cine xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="practica.xsd">
  <comidas>
    <comida>Palomitas</comida>
    <comida>Regalices</comida>
    <comida>Chocolate</comida>
    <comida>Ruffles</comida>
    <bebida>Fanta</bebida>
    <bebida>Coca-Cola</bebida>
    <bebida>Nestea</bebida>
    <bebida>Monster Energy</bebida>
  </comidas>

  <entradas>
    <entrada id="1">
      <id_pelicula>1</id_pelicula>
    </entrada>
    <entrada id="2">
      <id_pelicula>2</id_pelicula>
    </entrada>

  </entradas>

  <peliculas>
    <pelicula id="1">
      <nombre_peli>nobody</nombre_peli>
      <fecha_de_esteno>2021-06-20</fecha_de_esteno>
      <hora>10:30:00</hora>
      <hora>16:00:00</hora>

    </pelicula>

    <pelicula id="2">
      <nombre_peli>Cuñados</nombre_peli>
      <fecha_de_esteno>2021-04-10</fecha_de_esteno>
      <hora>20:15:00</hora>
      <hora>18:20:00</hora>

    </pelicula>

    <pelicula>
      <nombre_peli>Josep</nombre_peli>

    </pelicula>

  </peliculas>

  <usuarios>

    <usuario>
      <id_usu id="1"></id_usu>
      <nombre>ramon</nombre>
      <apellido>fernacez</apellido>

    </usuario>

    <usuario>
      <id_usu id="2"></id_usu>
      <nombre>jose</nombre>
      <apellido>Joseph</apellido>

    </usuario>

    <usuario>
      <id_usu id="3"></id_usu>
      <nombre>alex</nombre>

    </usuario>

  </usuarios>



</cine>
